# Generated by Django 2.1.2 on 2018-11-03 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartenir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitecommande', models.IntegerField()),
                ('livraisondemande', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False)),
            ],
            options={
                'db_table': 'appartenir',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('numcategorie', models.AutoField(primary_key=True, serialize=False)),
                ('nomcategorie', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datenaissanceclient', models.DateField()),
                ('pointsclient', models.IntegerField(default='0')),
                ('telephoneclient', models.CharField(blank=True, max_length=15)),
                ('codepostalclient', models.IntegerField(blank=True)),
                ('villeclient', models.CharField(blank=True, max_length=30)),
                ('rueclient', models.CharField(blank=True, max_length=30)),
                ('numclient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('numcommande', models.AutoField(primary_key=True, serialize=False)),
                ('montantcommande', models.FloatField(max_length=30)),
                ('datecommande', models.DateField(auto_now_add=True, verbose_name='Date de la commande')),
                ('numclient', models.ForeignKey(db_column='numclient', on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
            ],
            options={
                'db_table': 'commande',
            },
        ),
        migrations.CreateModel(
            name='Commenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(max_length=300)),
                ('note', models.IntegerField()),
                ('datecommentaire', models.DateField(auto_now_add=True, verbose_name='Date du commentaire')),
                ('numclient', models.ForeignKey(db_column='numclient', on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
            ],
            options={
                'db_table': 'commenter',
            },
        ),
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephonecommercant', models.CharField(max_length=15)),
                ('numcommercant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commercant',
            },
        ),
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('numsiret', models.BigIntegerField(help_text='Renseignez votre numèro de siret, 14 chiffres succesifs', primary_key=True, serialize=False)),
                ('nomcommerce', models.CharField(max_length=30)),
                ('typecommerce', models.CharField(max_length=30)),
                ('emailcommerce', models.EmailField(max_length=254)),
                ('livraisondisponible', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')])),
                ('telephonecommerce', models.CharField(max_length=15)),
                ('codepostalcommerce', models.IntegerField()),
                ('villecommerce', models.CharField(max_length=30)),
                ('ruecommerce', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'commerce',
            },
        ),
        migrations.CreateModel(
            name='Concerner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcategorie', models.ForeignKey(db_column='numcategorie', on_delete=django.db.models.deletion.CASCADE, to='app.Categorie')),
            ],
            options={
                'db_table': 'concerner',
            },
        ),
        migrations.CreateModel(
            name='Gerer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcommercant', models.ForeignKey(db_column='numcommercant', on_delete=django.db.models.deletion.CASCADE, to='app.Commercant')),
                ('numcommerce', models.ForeignKey(db_column='numcommerce', on_delete=django.db.models.deletion.CASCADE, to='app.Commerce')),
            ],
            options={
                'db_table': 'gerer',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('numproduit', models.AutoField(primary_key=True, serialize=False)),
                ('nomproduit', models.CharField(max_length=30)),
                ('marqueproduit', models.CharField(max_length=30)),
                ('descriptifproduit', models.TextField(max_length=400)),
                ('caracteristiquesproduit', models.TextField(max_length=400)),
                ('prixproduit', models.FloatField(max_length=30)),
                ('tauxremise', models.FloatField(max_length=5)),
                ('quantitestock', models.IntegerField(default='0')),
                ('quantitedisponible', models.IntegerField()),
                ('datelimitereservation', models.IntegerField(blank=True, null=True)),
                ('idcommerce', models.ForeignKey(db_column='idcommerce', on_delete=django.db.models.deletion.CASCADE, to='app.Commerce')),
                ('numcategorie', models.ForeignKey(db_column='numcategorie', on_delete=django.db.models.deletion.CASCADE, to='app.Categorie')),
            ],
            options={
                'db_table': 'produit',
            },
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('codereduction', models.AutoField(primary_key=True, serialize=False)),
                ('typereduction', models.CharField(choices=[('pourcentage', 'Taux de réduction en %'), ('bon', "Bon d'achat en euros")], max_length=15)),
                ('valeurreduction', models.FloatField(max_length=10)),
                ('estutilise', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')])),
                ('numclient', models.ForeignKey(db_column='numclient', on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
                ('numcommerce', models.ForeignKey(db_column='numcommerce', on_delete=django.db.models.deletion.CASCADE, to='app.Commerce')),
            ],
            options={
                'db_table': 'reduction',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('numreservation', models.AutoField(primary_key=True, serialize=False)),
                ('montantreservation', models.FloatField(max_length=30)),
                ('datereservation', models.DateField(auto_now_add=True, verbose_name='Date de la réservation')),
                ('numclient', models.ForeignKey(db_column='numclient', on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
                ('numcommerce', models.ForeignKey(db_column='numcommerce', on_delete=django.db.models.deletion.CASCADE, to='app.Commerce')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Reserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitereserve', models.IntegerField()),
                ('numproduit', models.ForeignKey(db_column='numproduit', on_delete=django.db.models.deletion.CASCADE, to='app.Produit')),
                ('numreservation', models.ForeignKey(db_column='numreservation', on_delete=django.db.models.deletion.CASCADE, to='app.Reservation')),
            ],
            options={
                'db_table': 'reserver',
            },
        ),
        migrations.AddField(
            model_name='concerner',
            name='numproduit',
            field=models.ForeignKey(db_column='numproduit', on_delete=django.db.models.deletion.CASCADE, to='app.Produit'),
        ),
        migrations.AddField(
            model_name='commenter',
            name='numproduit',
            field=models.ForeignKey(db_column='numproduit', on_delete=django.db.models.deletion.CASCADE, to='app.Produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='numcommerce',
            field=models.ForeignKey(db_column='numcommerce', on_delete=django.db.models.deletion.CASCADE, to='app.Commerce'),
        ),
        migrations.AddField(
            model_name='appartenir',
            name='numcommande',
            field=models.ForeignKey(db_column='numcommande', on_delete=django.db.models.deletion.CASCADE, to='app.Commande'),
        ),
        migrations.AddField(
            model_name='appartenir',
            name='numproduit',
            field=models.ForeignKey(db_column='numproduit', on_delete=django.db.models.deletion.CASCADE, to='app.Produit'),
        ),
        migrations.AlterUniqueTogether(
            name='reserver',
            unique_together={('numproduit', 'numreservation')},
        ),
        migrations.AlterUniqueTogether(
            name='gerer',
            unique_together={('numcommercant', 'numcommerce')},
        ),
        migrations.AlterUniqueTogether(
            name='concerner',
            unique_together={('numproduit', 'numcategorie')},
        ),
        migrations.AlterUniqueTogether(
            name='commenter',
            unique_together={('numproduit', 'numclient')},
        ),
        migrations.AlterUniqueTogether(
            name='appartenir',
            unique_together={('numproduit', 'numcommande')},
        ),
    ]
